name: Build and Deploy
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  REGEX_INCLUDE: "\\.(pdf|link|txt|c|java)$"

jobs:
  build:
    name: Create upload artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Generate build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-result
          path: .

  statik:
    name: Generate the static listing
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download compiled files
        uses: actions/download-artifact@v3
        with:
          name: build-result

      - name: Install go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.18.0"

      - name: Install statik
        run: go install github.com/lucat1/statik@latest

      - name: Update packages and install rsync
        run: sudo apt install rsync

      - name: Generate static directory listing
        run: $(go env GOPATH)/bin/statik -page .github/workflows/page.gohtml -l -b "https://${{ github.event.repository.owner.name }}.github.io/${{ github.event.repository.name }}/" -i "$REGEX_INCLUDE" site

      - name: Generate site artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v2
        with:
          name: statik-build
          path: ./site

  deploy:
    name: Deploy to Github Pages
    runs-on: ubuntu-latest

    needs: statik
    if: github.ref == 'refs/heads/main'

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Download static site artifact
        uses: actions/download-artifact@v3
        with:
          name: statik-build
          path: site

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
